stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker --version
    - echo $TAG_LATEST
    - echo $TAG_COMMIT

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - echo $TAG_LATEST
    - echo $TAG_COMMIT
    

