stages:
  - prep
  - build
  - test

prepare the project:
  stage: prep
  script:
    - cat src/app/dto/my_folder.ts
    - mkdir test_folder
    - touch test_folder/testfile.txt
  artifacts:
    paths:
      - test_folder/

build the project:
  stage: build
  script:
    - cd test_folder
    - echo "test text" >> testfile.txt
    - echo "aaaa" >> testfile.txt
  artifacts:
    paths:
      - test_folder/

test the project:
  stage: test
  script:
    - test -f test_folder/testfile.txt
    - cd test_folder
    - grep "test text" testfile.txt
