stages:
  - build
  - test

build the project:
  stage: build
  script:
    - mkdir test_folder
    - touch test_folder/testfile.txt
    - cd test_folder
    - echo "test text" > testfile.txt
  artifacts:
    - test_folder/

test the project:
  stage: test
  script:
    - test -f test_folder/testfile.txt
    - cd test_folder
    - grep "test text" testfile.txt
