stages:
  - build
  - test

build website:
  stage: build
  image: node:12.19.0
  script:
    - npm --version
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - ./dist

test artifact:
  stage: test
  image: alpine
  script: 
    - grep -q "mat" ./dist/data-management-frontend/styles.css

test website:
  stage: test
  image: node:12.19.0
  script:
    - npm install
    - npm start
    - curl "http://localhost:4200"

