stages:
  - build
  - test

build website:
  stage: build
  image: node:12.19.0
  script:
    - npm --version
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - ./dist

test artifact:
  stage: test
  script: 
    - grep "mat" ./dist/data-management-frontend/styles.css

